---
title: "INCLASS_13"
output:
  pdf_document: default
  html_document: default
date: "2022-11-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Composition Sampling

Preliminaries:

$$
P(X=1) = 0.8\\
P(X=0) = 0.2\\
$$

$$
P(Y=1|X=0)=\frac{P(Y=1\& X=0)}{P(X=0)} = \frac{0.1}{0.2} = 0.5\\
P(Y=1|X=1)=\frac{p(Y=1\& X=1)}{P(X=1)} = \frac{0.6}{0.8} = \frac{3}{4}
$$

Sampling:

```{r}
x = rep(-1, 100000)
y = rep(-1, 100000)
for (i in 1:100000){
  x[i] = sample(c(0, 1), size=1, prob=c(0.2, 0.8))
  if (x[i]==0){
    y[i] = sample(c(0, 1), size=1, prob=c(0.5, 0.5))
  }
  else{
    y[i] = sample(c(0, 1), size=1, prob=c(1/4, 3/4))
  }
}
```

Check:

```{r}
cat(mean(x), '\n')
cat(mean(y), '\n')
cat(mean((x==0)&(y==0)), '\n')
cat(mean((x==0)&(y==1)), '\n')
cat(mean((x==1)&(y==0)), '\n')
cat(mean((x==1)&(y==1)), '\n')
```


## Gibbs Sampler

Preliminaries:

```{r}
p = matrix(c(0.5, 3/4, 2/3, 6/7), nrow=2)

x = rep(NA, 100000)
y = rep(NA, 100000)

x[1] = 1
y[1] = sample(c(0, 1), size=1, prob = c(1-p[1, x[1]+1], p[1, x[1]+1]))
```

Sampling:

```{r}
for (i in 2:100000){
  x[i] = sample(c(0, 1), size=1, prob = c(1-p[2, y[i-1]+1], p[2, y[i-1]+1]))
  y[i] = sample(c(0, 1), size=1, prob = c(1-p[1, x[i]+1], p[1, x[i]+1]))
}
```

Check:

```{r}
cat(mean(x), '\n')
cat(mean(y), '\n')
cat(mean((x==0)&(y==0)), '\n')
cat(mean((x==0)&(y==1)), '\n')
cat(mean((x==1)&(y==0)), '\n')
cat(mean((x==1)&(y==1)), '\n')
```











